##############################################
# Doc：https://cspell.org
##############################################

version: '0.2'

# prettier-ignore
words:
  - chronous                    # 时钟

ignoreWords: []
